### ISSUE TITLE
Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by kanishk-mehta** [bjnortier/dxf#36]
Hi,

When I try to use the command line tool, the dxf file is converted to svg flawlessly, but when I try to follow the steps mentioned in the Readme, i end up with this error - Cannot read property 'reduce' of undefined.

Am new at this so if please let me know if any more/other information is required. Please help @bjnortier 

Thank you!

**Comment by bjnortier** [comment]
Hi

Can you please supply:
1. The DXF file
2. The exact steps to reproduce the error
3. The exact error stack trace (which includes the file and line generating the error)

**Comment by bjnortier** [comment]
Struggling to reproduce the problem.

Are you sure you're using the result from dxf.parseString() as ain input to dxf.toSVG()?

1. What happens if you use the dxf.html in the "examples" folder to open the file? 
2. Can you run the following in a node instance and paste *exactly* the output. It doesn't help if you indicate the error without the actual file/line number of the error:

```
$ node
> var dxf = require('dxf')
> var parsed = dxf.parseString(fs.readFileSync('<path>/api-cw750-details.dxf', 'utf-8'))
> console.log(parsed.blocks.length)
324
> var denormed = dxf.denormalise(parsed)
> var svg = dxf.toSVG(parsed)
> console.log(svg.length)
1566882
```

**Comment by bjnortier** [comment]
No response so I'm closing
