### ISSUE TITLE
Thoughts on canvas

### ISSUE THREAD

**Issue by davidgilbertson** [bjnortier/dxf#40]
Most of the DXFs I deal with have hundreds of thousands of points and SVG tends to struggle.
So, I'd like to use a `<canvas>`. My plan at the moment is to use your `toSVG()`, then extract the `d` attribute out of each `<path>` and pass it to the [Path2D](https://developer.mozilla.org/en-US/docs/Web/API/Path2D/Path2D) constructor (which accepts an SVG path string, and can then be rendered to a canvas).

But it isn't ideal for me to get a whole SVG string, then mount it as a DOM node to traverse over it to extract the paths.

Would you consider separating the 'get paths from DXF' part of the function from the 'build SVG string' part? (Or accepting a PR that does?)

It would still need to return the bounding box and colour data.

Edit: feel free to close this issue since it's just a question.

**Comment by bjnortier** [comment]
Jip it's not ideal, and this is something I've been thinking about.

The original aim of the library was to render DXFs on a WebGL canvas. WebGL has no line primitives likes <circle /> etc. like SVG does, so everything is interpolated, which is silly as an SVG renderer should be able to use native <circle /> etc. primitives.

As you describe those two steps should be separated, which I've been thinking about for a new version (v4), because it's major change to how the library works.

**Comment by davidgilbertson** [comment]
Looks good! I won't get a chance to check it out until next week, but this could make a big difference to the project I'm working on. Your efforts are much appreciated!

I'll close this now, re-open if you want to keep it to track the other stuff.

P.S. I look forward to sharing once it's done.
