### ISSUE TITLE
Transfer maintenance/ownership

### ISSUE THREAD

**Issue by bjnortier** [bjnortier/dxf#86]
I need to transfer ownership or maintenance of this package as I don't develop in this area anymore. Any suggestions on how to handle this?

**Comment by skymakerolof** [comment]
Thank you @bjnortier for creating this project and maintaining it for as long as you have!

Since we're using this package at my company, I'm open to taking over the maintenance responsibility. I have the same user account name on GitHub and npm.

I have never been involved in transferring ownership before, but I found a guide for GitHub here: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

There's also a guide for npm here:
https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

If you'd like to keep ownership I believe it's also possible to add me as a co-maintainer on both GitHub and npm.

**Comment by z3dev** [comment]
FYI, we (JSCAD) created a super user account which controls all project access, administrative settings, email, etc. So, if the main person wants to walk away then it’s very simple to give up everything.

@skymakerolof probably has the best suggestion. If that doesn’t work out then a full transfer can be done later.

**Comment by bjnortier** [comment]
Ok thanks @skymakerolof. I will transfer it to you

**Comment by bjnortier** [comment]
@skymakerolof I couldn't transfer it to you on Github because you already have repo names "dxf", so I added you as a collaborator. Also added you as a maintainer on NPM

**Comment by skymakerolof** [comment]
Thank you!

**Comment by bjnortier** [comment]
@skymakerolof can I transfer this repo to you properly?

**Comment by skymakerolof** [comment]
> @skymakerolof can I transfer this repo to you properly?

@bjnortier Absolutely! I have removed the dxf repository that was on my account, so I think you should be able to now.

**Comment by bjnortier** [comment]
Thanks! Transferred
